### ISSUE TITLE
Create shell gmail account for admin user

### ISSUE THREAD

**Issue by itsazoo** [seng499-company1/backend#118]
# Description 
We need a valid gmail account to authenticate sending the reminder email for the /remind endpoint. Ideally admin would have registered valid gmail creds with our system but that is out of scope therefore for demo purposes we need to create a shell gmail account to represent the admin user. 

Once the account is created we will hardcode the creds into /remind endpoint. 

# Related issue
#117

**Comment by owenjaques** [comment]
> Once the account is created we will hardcode the creds into /remind endpoint.

This really isn't secure which is why I mentioned in the PR that I will fill them out on the deployment. I already have an account set up to use this.
