### ISSUE TITLE
Modify Schedule API to deal with history of prof preferences use case

### ISSUE THREAD

**Issue by ekanemeinstein** [seng499-company1/backend#119]
- We have implemented support for saving a history of prof preferences yearly. 
- Each prof has one set of preferences for each year. 
- We have not made an adjustment in the Algo input to deal with this.

**Current Behaviour:**
Sends all prof preferences for each prof to algo.

**Expected Behaviour:**
Modify query to send algo latest preferences for each prof.
Suggestion ( Use timestamp )

**Comment by itsazoo** [comment]
Resolved
