### ISSUE TITLE
Upgrade Company 2 Algo packages

### ISSUE THREAD

**Issue by ekanemeinstein** [seng499-company1/backend#142]
Latest releases for Company 2 Algos

- [ ] [coursescheduler==0.1.2](https://pypi.org/project/coursescheduler/).
- [ ] [capacityforecaster==0.3.4](https://test.pypi.org/project/capacityforecaster/).
- [ ] Test that docker still builds fine with after upgrade and also with fresh build (containers deleted).

**Comment by itsazoo** [comment]
Resolved
